authentication:
    build:
        context: ./authentication-service-twtg
    environment:
        - API_AUTHENTICATION_PORT=${API_AUTHENTICATION_PORT}
        - PAGINATION_LIMIT=${PAGINATION_LIMIT}
        - PAGINATION_SORT=${PAGINATION_SORT}
        - SEQUELIZE_USERNAME=${SEQUELIZE_USERNAME}
        - SEQUELIZE_PASSWORD=${SEQUELIZE_PASSWORD}
        - SEQUELIZE_DATABASE=${SEQUELIZE_DATABASE}
        - SEQUELIZE_HOST=${SEQUELIZE_HOST}
        - SEQUELIZE_DIALECT=${SEQUELIZE_DIALECT}
        - SEQUELIZE_PORT=${SEQUELIZE_PORT}
        - SSH_PRIVATE=${SSH_PRIVATE}
        - SSH_PUBLIC=${SSH_PUBLIC}
        - SSH_KNOWN_HOSTS=${SSH_KNOWN_HOSTS}
        - WAIT_HOSTS=postgis:5432
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
        - private-network
    depends_on:
        - postgis
    labels:
        - traefik.enable=true
        - traefik.http.routers.authentication.rule=PathPrefix(`/authentication`)
        - traefik.http.routers.authentication.entryPoints=web
        - traefik.http.routers.authentication.service=authentication-service
        - traefik.http.services.authentication-service.loadbalancer.server.port=${API_AUTHENTICATION_PORT}
        - traefik.docker.network=private-network
    catalogs:
        build:
            context: ./catalogs-service-twtg
        environment:
            - API_CATALOGS_PORT=${API_CATALOGS_PORT}
            - PAGINATION_LIMIT=${PAGINATION_LIMIT}
            - PAGINATION_SORT=${PAGINATION_SORT}
            - SEQUELIZE_USERNAME=${SEQUELIZE_USERNAME}
            - SEQUELIZE_PASSWORD=${SEQUELIZE_PASSWORD}
            - SEQUELIZE_DATABASE=${SEQUELIZE_DATABASE}
            - SEQUELIZE_HOST=${SEQUELIZE_HOST}
            - SEQUELIZE_DIALECT=${SEQUELIZE_DIALECT}
            - SEQUELIZE_PORT=${SEQUELIZE_PORT}
            - SSH_PRIVATE=${SSH_PRIVATE}
            - SSH_PUBLIC=${SSH_PUBLIC}
            - SSH_KNOWN_HOSTS=${SSH_KNOWN_HOSTS}
            - WAIT_HOSTS=postgis:5432
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
        networks:
            - private-network
        depends_on:
            - postgis
        labels:
            - traefik.enable=true
            - traefik.http.routers.catalogs.rule=PathPrefix(`/catalogs`)
            - traefik.http.routers.catalogs.entryPoints=web
            - traefik.http.routers.catalogs.service=catalogs-service
            - traefik.http.services.catalogs-service.loadbalancer.server.port=${API_CATALOGS_PORT}
            - traefik.docker.network=private-network
        ports:
            - ${API_CATALOGS_PORT}:${API_CATALOGS_PORT}    
